INSERT INTO bears VALUES (1,"Mr. Chocolate", 20, "M", "dark brown", "calm", 0);
INSERT INTO bears VALUES (2,"Rowdy", 10, "M", "black", "intense", 1);
INSERT INTO bears VALUES (3,"Tabitha", 6, "F", "dark brown", "Nice", 1);
INSERT INTO bears VALUES (4,"Sargeant Brown", 19, "M", "Green", "Slimy", 0);
INSERT INTO bears VALUES (5,"Melissa", 13, "F", "dark brown", "goofy", 1);
INSERT INTO bears VALUES (6,"Grinch", 2, "M", "Black", "Grinchy", 1);
INSERT INTO bears VALUES (7,"Wendy", 6, "F", "Blue", "naive", 1);
INSERT INTO bears VALUES (8,null, 20, "M", "black", "aggressive", 0);
INSERT INTO bears VALUES (9,"Mr. Chocolate", 3, "F", "Brown", "relaxed", 1);
INSERT INTO bears VALUES (10,"Rowdy", 2, "M", "Light Brown", "funny", 1);
INSERT INTO bears VALUES (11,"Tabitha", 4, "F", "Black", "angry", 1);
INSERT INTO bears VALUES (12,"Sergeant Brown", 3, "M", "White", "goofy", 1);
INSERT INTO bears VALUES (13,"Melissa", 6, "F", "Brown", "mad", 1);
INSERT INTO bears VALUES (14,"Grinch", 1, "M", "Black", "happy", 1);
INSERT INTO bears VALUES (15,"Wendy", 5, "M", "Brown", "sad", 1);
INSERT INTO bears VALUES (16, null, 3, "F", "Light Brown", "naive", 1);